---
title: "ARU data processing on BirdNET for Birds Canada (west)"
#author: "Sunny Tseng"
#date: "`r Sys.Date()`"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Introduction

The ARU data was collected by Birds Canada during 2023 breeding season in the area of Chilcotin, Cariboo, BC, Canada. A total of 21 sites were set up, with each site having 2 ARU locations. The goal of this repository is to analyzing all the ARU recordings that collected from this project through BirdNET, and provide detection information for each of the ARU.

## Workflow

1.  Data organization
2.  Data exploration
3.  Processing data through BirdNET GUI
4.  Data wrangling and cleaning
5.  Final summarizing

## BirdNET Analyzer GUI settings

All the analyses were done on [BirdNET Analyzer](https://github.com/kahst/BirdNET-Analyzer) GUI on Windows. The model version that used in the GUI is *BirdNET_GLOBAL_6K_V2.4_Model_FP32.tfile*.

-   Species by location: setting the location and time would enhance the precision of detection.
    -   latitude: 51 or 52, base on site location
    -   longitude: -121 or -122, base on site location
    -   week: 24, mid June, base on the time that the recording was made
-   Inference settings
    -   Minimum confidence: 0.5 (default)
    -   Sensitivity: 1 (default)
    -   Overlap: 0 (default)
-   Other settings
    -   Result type: R
    -   Batch size: 4
    -   Threads: 4

## Output

-   One excel file was produced for each site, each ARU, with the following naming rule: `site_location_aruid_type.csv`
-   Each row of the data frame represents single BirdNET detection
-   Columns of the data set are explained below:

+-----------------+--------------------------------------------------------------------------------------------------------------------------+
| Column name     | Description                                                                                                              |
+=================+==========================================================================================================================+
| site            | the site name of ARU employment, one of the 21 sites                                                                     |
+-----------------+--------------------------------------------------------------------------------------------------------------------------+
| location        | value being 1 or 2. The first or the second location of ARU within each site                                             |
+-----------------+--------------------------------------------------------------------------------------------------------------------------+
| aru_id          | a 4 digits number. Unique ID of each ARU unit                                                                            |
+-----------------+--------------------------------------------------------------------------------------------------------------------------+
| type            | "Mini" or "BAR-LT"                                                                                                       |
+-----------------+--------------------------------------------------------------------------------------------------------------------------+
| date            | the date of detection, with the format yyyymmdd                                                                          |
+-----------------+--------------------------------------------------------------------------------------------------------------------------+
| hour            | the hour of detection                                                                                                    |
+-----------------+--------------------------------------------------------------------------------------------------------------------------+
| start           | within a specific recording, where is the start time of the detection                                                    |
+-----------------+--------------------------------------------------------------------------------------------------------------------------+
| end             | within a specific recording, where is the end time of the detection                                                      |
+-----------------+--------------------------------------------------------------------------------------------------------------------------+
| scientific_name | scientific name of the detected species                                                                                  |
+-----------------+--------------------------------------------------------------------------------------------------------------------------+
| common_name     | common name of the detected species                                                                                      |
+-----------------+--------------------------------------------------------------------------------------------------------------------------+
| confidence      | confidence value for the detection provided by BirdNET. Higher confidence corresponded to higher probability of presence |
+-----------------+--------------------------------------------------------------------------------------------------------------------------+
| filepath        | file path of the original recording file                                                                                 |
+-----------------+--------------------------------------------------------------------------------------------------------------------------+

## Processing schedule & Output

-   [Working notes](./docs/working-notes.md)
-   Full list of BirdNET output files can be found for [All Species](./data/cleaned/all) and [Focal Species](./data/cleaned/focal)

+---------------------+----------+--------+--------+--------+--------------------+----------------------------------------------------------------+----------------------+
| Site                | Location | ARU ID | Type   | Date   | Time               | Output                                                         | Note                 |
+=====================+==========+========+========+========+====================+================================================================+======================+
| Axe Lake            | 1        | 9126   | BAR-LT | Dec.04 | 17:10 - 20:46      | [file](./data/cleaned/all/AxeLake_1_9126_BARLT.csv)            | 3.5 hr               |
+---------------------+----------+--------+--------+--------+--------------------+----------------------------------------------------------------+----------------------+
| Axe Lake            | 2        | 7859   | Mini   | Dec.04 | 21:20 - 22:30      | [file](./data/cleaned/all/AxeLake_2_7859_Mini.csv)             | 1.5 hr               |
+---------------------+----------+--------+--------+--------+--------------------+----------------------------------------------------------------+----------------------+
| Baptiste Meadow     | 1        | 9742   | BAR-LT | Dec.06 | 10:19 - 12:32      | [file](./data/cleaned/all/BaptisteMeadow_1_9742_BARLT.csv)     | 2 hr                 |
+---------------------+----------+--------+--------+--------+--------------------+----------------------------------------------------------------+----------------------+
| Baptiste Meadow     | 2        | 9441   | BAR-LT | Dec.04 | 22:40 - 9:00 (+1)  | [file](./data/cleaned/all/BaptisteMeadow_2_9441_BARLT.csv)     |                      |
+---------------------+----------+--------+--------+--------+--------------------+----------------------------------------------------------------+----------------------+
| Big Creek Control   | 1        | 9089   | BAR-LT | Dec.06 | 13:08 - 14:46      | [file](./data/cleaned/all/BigCreekControl_1_9089_BARLT.csv)    | 1.5 hr               |
+---------------------+----------+--------+--------+--------+--------------------+----------------------------------------------------------------+----------------------+
| Big Creek Control   | 2        | 9515   | BAR-LT | Dec.08 | 10:20 -            | [file](./data/cleaned/all/BigCreekControl_2_9515_BARLT.csv)    | 1.5 hr               |
|                     |          |        |        |        |                    |                                                                |                      |
|                     |          |        |        |        | 11:52              |                                                                |                      |
+---------------------+----------+--------+--------+--------+--------------------+----------------------------------------------------------------+----------------------+
| Burnson Lake        | 1        | 7915   | Mini   | Dec.06 | 14:58 - 16:20      | [file](./data/cleaned/all/BurnsonLake_1_7915_Mini.csv)         | 1.5 hr               |
+---------------------+----------+--------+--------+--------+--------------------+----------------------------------------------------------------+----------------------+
| Burnson Lake        | 2        | 9214   | BAR-LT | Dec.06 | 16:20 - 18:10      | [file](./data/cleaned/all/BurnsonLake_2_9214_BARLT.csv)        | 2 hr                 |
+---------------------+----------+--------+--------+--------+--------------------+----------------------------------------------------------------+----------------------+
| Chilco Ranch        | 1        | 9807   | BAR-LT | Dec.08 | 19:09 - 20:36      | [file](./data/cleaned/all/ChilcoRanch_1_9807_BARLT.csv)        | Run in batch (below) |
+---------------------+----------+--------+--------+--------+--------------------+----------------------------------------------------------------+----------------------+
| Chilco Ranch        | 2        | 9603   | BAR-LT | Dec.08 | 17:41 - 19:08      | [file](./data/cleaned/all/ChilcoRanch_2_9603_BARLT.csv)        |                      |
+---------------------+----------+--------+--------+--------+--------------------+----------------------------------------------------------------+----------------------+
| Colpitt Lake        | 1        | 8792   | BAR-LT | Dec.08 | 21:57 - 23:50      | [file](./data/cleaned/all/ColpittLake_1_8792_BARLT.csv)        |                      |
+---------------------+----------+--------+--------+--------+--------------------+----------------------------------------------------------------+----------------------+
| Colpitt Lake        | 2        | 7255   | Mini   | Dec.08 | 20:46 - 21:57      | [file](./data/cleaned/all/ColpittLake_2_7255_Mini.csv)         |                      |
+---------------------+----------+--------+--------+--------+--------------------+----------------------------------------------------------------+----------------------+
| Dog Creek Road      | 1        | 9029   | BAR-LT | Dec.09 | 00:34 - 02:35      | [file](./data/cleaned/all/DogCreekRoad_1_9029_BARLT.csv)       |                      |
+---------------------+----------+--------+--------+--------+--------------------+----------------------------------------------------------------+----------------------+
| Dog Creek Road      | 2        | 7245   | Mini   | Dec.08 | 11:56 - 00:34 (+1) | [file](./data/cleaned/all/DogCreekRoad_2_7245_Mini.csv)        |                      |
+---------------------+----------+--------+--------+--------+--------------------+----------------------------------------------------------------+----------------------+
| Enterprise Road     | 1        | 9270   | BAR-LT | Dec.09 | 2:36 - 4:36        | [file](./data/cleaned/all/EnterpriseRoad_1_9270_BARLT.csv)     | Location was NA      |
+---------------------+----------+--------+--------+--------+--------------------+----------------------------------------------------------------+----------------------+
| Fiftynine Creek     | 1        | 9782   | BAR-LT | Dec.09 | 6:52 - 9:05        | [file](./data/cleaned/all/FiftynineCreek_1_9782_BARLT.csv)     |                      |
+---------------------+----------+--------+--------+--------+--------------------+----------------------------------------------------------------+----------------------+
| Fiftynine Creek     | 2        | 8990   | BAR-LT | Dec.09 | 4:37 - 6:51        | [file](./data/cleaned/all/FiftynineCreek_2_8990_BARLT.csv)     |                      |
+---------------------+----------+--------+--------+--------+--------------------+----------------------------------------------------------------+----------------------+
| Helena Conservation | 1        | 9235   | BAR-LT | Dec.11 | 14:03 - 16:24      | [file](./data/cleaned/all/HelenaConservation_1_9235_BARLT.csv) | Run in batch (below) |
+---------------------+----------+--------+--------+--------+--------------------+----------------------------------------------------------------+----------------------+
| Helena Conservation | 2        | 9140   | BAR-LT | Dec.11 | 11:16 - 14:02      | [file](./data/cleaned/all/HelenaConservation_2_9140_BARLT.csv) |                      |
+---------------------+----------+--------+--------+--------+--------------------+----------------------------------------------------------------+----------------------+
| Helena Lake         | 1        | 9621   | BAR-LT | Dec.11 | 18:42 - 20:51      | [file](./data/cleaned/all/HelenaLake_1_9621_BARLT.csv)         |                      |
+---------------------+----------+--------+--------+--------+--------------------+----------------------------------------------------------------+----------------------+
| Helena Lake         | 2        | 8923   | BAR-LT | Dec.11 | 16:25 - 18:41      | [file](./data/cleaned/all/HelenaLake_2_8923_BARLT.csv)         |                      |
+---------------------+----------+--------+--------+--------+--------------------+----------------------------------------------------------------+----------------------+
| Lilypad Lake        | 1        | 8860   | BAR-LT | Dec.11 | 22:18 - 00:20 (+1) | [file](./data/cleaned/all/LilypadLake_1_8860_BARLT.csv)        |                      |
+---------------------+----------+--------+--------+--------+--------------------+----------------------------------------------------------------+----------------------+
| Lilypad Lake        | 2        | 7836   | Mini   | Dec.11 | 21:02 - 22:08      | [file](./data/cleaned/all/LilypadLake_2_7836_Mini.csv)         |                      |
+---------------------+----------+--------+--------+--------+--------------------+----------------------------------------------------------------+----------------------+
| Murphy Lake         | 1        | 6663   | Mini   | Dec.12 | 00:32 - 1:53       | [file](./data/cleaned/all/MurphyLake_1_6663_Mini.csv)          |                      |
+---------------------+----------+--------+--------+--------+--------------------+----------------------------------------------------------------+----------------------+
| Murphy Lake         | 2        | 7710   | Mini   | Dec.12 | 2:04 - 3:25        | [file](./data/cleaned/all/MurphyLake_2_7710_Mini.csv)          |                      |
+---------------------+----------+--------+--------+--------+--------------------+----------------------------------------------------------------+----------------------+
| Pete Kitchen Lake   | 1        | 9058   | NA     | NA     | NA                 | NA                                                             | empty folder         |
+---------------------+----------+--------+--------+--------+--------------------+----------------------------------------------------------------+----------------------+
| Pete Kitchen Lake   | 2        | 9205   | BAR-LT | Dec.12 | 3:25 - 5:28        | [file](./data/cleaned/all/PeteKitchenLake_2_9205_BARLT.csv)    |                      |
+---------------------+----------+--------+--------+--------+--------------------+----------------------------------------------------------------+----------------------+
| Tatton Lake         | 1        | 6705   | Mini   | Dec.12 | 11:11 - 12:40      | [file](./data/cleaned/all/TattonLake_1_6705_Mini.csv)          | Run in batch (below) |
+---------------------+----------+--------+--------+--------+--------------------+----------------------------------------------------------------+----------------------+
| Tatton Lake         | 2        | 9633   | BAR-LT | Dec.12 | 12:41 - 15:08      | [file](./data/cleaned/all/TattonLake_2_9633_BARLT.csv)         |                      |
+---------------------+----------+--------+--------+--------+--------------------+----------------------------------------------------------------+----------------------+
| Thaddus Lake        | 1        | 9584   | BAR-LT | Dec.12 | 16:56 - 19:28      | [file](./data/cleaned/all/Thaddus_1_9584_BARLT.csv)            |                      |
+---------------------+----------+--------+--------+--------+--------------------+----------------------------------------------------------------+----------------------+
| Thaddus Lake        | 2        | 5976   | Mini   | Dec.12 | 15:21 - 16:56      | [file](./data/cleaned/all/Thaddus_2_5976_Mini.csv)             |                      |
+---------------------+----------+--------+--------+--------+--------------------+----------------------------------------------------------------+----------------------+
| Watson Creek        | 1        | 9157   | BAR-LT | Dec.12 | 21:06 - 23:28      | [file](./data/cleaned/all/WatsonCreek_1_9157_BARLT.csv)        |                      |
+---------------------+----------+--------+--------+--------+--------------------+----------------------------------------------------------------+----------------------+
| Watson Creek        | 2        | 7759   | Mini   | Dec.12 | 19:40 - 21:07      | [file](./data/cleaned/all/WatsonCreek_2_7759_Mini.csv)         |                      |
+---------------------+----------+--------+--------+--------+--------------------+----------------------------------------------------------------+----------------------+
| Wildhorse Meadow    | 1        | 9072   | BAR-LT | Dec.12 | 23:29 - 1:50 (+1)  | [file](./data/cleaned/all/WildhorseMeadow_1_9072_BARLT.csv)    |                      |
+---------------------+----------+--------+--------+--------+--------------------+----------------------------------------------------------------+----------------------+
| Wildhorse Meadow    | 2        | 9799   | BAR-LT | Dec.13 | 1:50 - 4:10        | [file](./data/cleaned/all/WildhorseMeadow_2_9799_BARLT.csv)    |                      |
+---------------------+----------+--------+--------+--------+--------------------+----------------------------------------------------------------+----------------------+
| Winthrow Creek      | 1        | 9065   | BAR-LT | Dec.13 | 4:11 - 6:31        | [file](./data/cleaned/all/WinthrowCreek_1_9065_BARLT.csv)      |                      |
+---------------------+----------+--------+--------+--------+--------------------+----------------------------------------------------------------+----------------------+
| Winthrow Creek      | 2        | 9171   | BAR-LT | Dec.13 | 6:31 - 8:53        | [file](./data/cleaned/all/WinthrowCreek_2_9171_BARLT.csv)      |                      |
+---------------------+----------+--------+--------+--------+--------------------+----------------------------------------------------------------+----------------------+
